name: Build Android 15 GKI 6.6

on:
  workflow_call:
    inputs:
      make_release:
        required: true
        type: boolean
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string
      require_susfs:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v3

      - name: Call GKI builder
        uses: ./.github/workflows/gki-kernel.yml
        with:
          android_version: "android15"
          kernel_version: "6.6"
          sub_level: "98"
          make_release: ${{ inputs.make_release }}
          kernelsu_variant: ${{ inputs.kernelsu_variant }}
          kernelsu_branch: ${{ inputs.kernelsu_branch }}
          kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
          require_susfs: true
