name: Build and Release GKI Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: "Create GitHub release?"
        type: boolean
        default: true

      build_a15:
        description: "Build Android 15 (6.6 + SUSFS)"
        type: boolean
        default: false

jobs:
  android15:
    if: ${{ inputs.build_a15 }}
    uses: ./.github/workflows/kernel-wrapper.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      android_version: android15
      kernel_version: "6.6"
      sub_level: "102"
      os_patch_level: "2025-10"
      require_susfs: true   # ✅ HIER ändern
