name: Android 12 5.10

permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      make_release:
        required: true
        type: boolean
        default: true

jobs:
  build-kernel-a12-5-10:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "237"
            os_patch_level: "2025-06"
            revision: "r1"

    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}
