name: Android 15 6.6

permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string
      require_susfs:              # ✅ HINZUGEFÜGT
        required: false
        type: boolean
        default: true

jobs:
  build-kernel-a15-6-6-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "98"
            os_patch_level: "2025-09"

    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit

    with:
      make_release: ${{ inputs.make_release }}
      android_version: "android15"
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
      require_susfs: ${{ inputs.require_susfs }}   # ✅ WEITERGEREICHT
